import 'package:bloc/bloc.dart';
import 'package:code_swift/core/models/error_model.dart';
import 'package:code_swift/core/models/vehicle_model.dart';
import 'package:code_swift/core/repo/vehicle_repo.dart';




part 'vehicle_state.dart';

class VehicleCubit extends Cubit<VehicleState> {
  final VehicleRepo repo;
  VehicleCubit(this.repo) : super(VehicleInitial());

  Future<void>getVehicleDetails()async{

    emit(VehicleFetchLoading());
    final data=await repo.getVehicleDetails();
    // VehicleModel vehicleModel=VehicleModel.fromJson({
    //     "name": "STO-ITEM-2024-00005",
    //     "owner": "divyanshsingh.divs@gmail.com",
    //     "creation": "2024-04-01 23:10:29.560805",
    //     "modified": "2024-06-27 14:49:31.493548",
    //     "modified_by": "testadmin@example.com",
    //     "docstatus": 0,
    //     "idx": 0,
    //     "naming_series": "STO-ITEM-.YYYY.-",
    //     "item_code": "STO-ITEM-2024-00005",
    //     "item_name": "TATA MOTORS TRUCK TEST NEW",
    //     "item_group": "Bus",
    //     "gst_hsn_code": "870410",
    //     "is_nil_exempt": 0,
    //     "is_non_gst": 0,
    //     "stock_uom": "Nos",
    //     "disabled": 0,
    //     "allow_alternative_item": 0,
    //     "is_stock_item": 1,
    //     "has_variants": 0,
    //     "include_item_in_manufacturing": 1,
    //     "opening_stock": 0.0,
    //     "valuation_rate": 0.0,
    //     "standard_rate": 0.0,
    //     "is_fixed_asset": 0,
    //     "auto_create_assets": 0,
    //     "is_grouped_asset": 0,
    //     "over_delivery_receipt_allowance": 0.0,
    //     "over_billing_allowance": 0.0,
    //     "description": "<div><p>30 SEATER AC BUS</p></div>",
    //     "brand": "Ashok Leyland",
    //     "shelf_life_in_days": 0,
    //     "end_of_life": "2099-12-31",
    //     "default_material_request_type": "Purchase",
    //     "valuation_method": "",
    //     "weight_per_unit": 0.0,
    //     "allow_negative_stock": 0,
    //     "has_batch_no": 0,
    //     "create_new_batch": 0,
    //     "has_expiry_date": 0,
    //     "retain_sample": 0,
    //     "sample_quantity": 0,
    //     "has_serial_no": 0,
    //     "variant_based_on": "Item Attribute",
    //     "min_order_qty": 0.0,
    //     "safety_stock": 0.0,
    //     "is_purchase_item": 1,
    //     "lead_time_days": 0,
    //     "last_purchase_rate": 0.0,
    //     "is_customer_provided_item": 0,
    //     "delivered_by_supplier": 0,
    //     "enable_deferred_expense": 0,
    //     "no_of_months_exp": 0,
    //     "grant_commission": 1,
    //     "is_sales_item": 1,
    //     "max_discount": 0.0,
    //     "enable_deferred_revenue": 0,
    //     "no_of_months": 0,
    //     "inspection_required_before_purchase": 0,
    //     "inspection_required_before_delivery": 0,
    //     "is_sub_contracted_item": 0,
    //     "custom_title": "ASHOK LEYLAND ",
    //     "custom_registration_number": "NL01B1680",
    //     "custom_vehicle_registration": "NL01",
    //     "custom_state": "Nagaland",
    //     "custom_engine_number": "KEEZ413436",
    //     "custom_chassis_number": "MB1PREHD4KEED7747",
    //     "custom_vehicle_class": "Bus",
    //     "custom_model": "TF1812",
    //     "custom_vehicle_make": "2019-05-01",
    //     "custom_fuel_type": "Diesel",
    //     "custom_manufacturing_month_and_year": "2019-05-01",
    //     "custom_vehicle_type": "BUSES",
    //     "custom_gvw_in_kgs": 16200.0,
    //     "custom_unladen_weight_in_kgs": 9450.0,
    //     "custom_vehicle_color": "Blue and Green",
    //     "custom_odometer_reading_in_km": 348326.0,
    //     "custom_seating_capacity": 31,
    //     "custom_sleeper_capacity": 0,
    //     "custom_no_of_axels": 2,
    //     "custom_mark_as_sold": 0,
    //     "custom_no_of_views": "415",
    //     "custom_no_of_bids": "14",
    //     "custom_bus_type": "Seater",
    //     "custom_ac_status": "AC",
    //     "custom_window_type": "Fixed",
    //     "custom_seat_manufacturer": "Harita Unominda",
    //     "custom_body_manufacturer": "Prakash",
    //     "custom_insurance_declared_value": 3600000.0,
    //     "custom_insurance_validity": "2024-05-23",
    //     "custom_ncb": 1,
    //     "custom_accident_history": 0,
    //     "custom_fitness_certificate": "YES",
    //     "custom_fitness_certificate_valid_till": "2024-04-28",
    //     "custom_pucc_certificate": 1,
    //     "custom_pucc_expiry": "2024-04-28",
    //     "custom_upload_fitness_certificate": "/files/B1679.pdf",
    //     "custom_noc_available": 1,
    //     "custom_tax_paid": 1,
    //     "custom_taxes_paid_upto_date": "2024-04-16",
    //     "custom_police_verification": 1,
    //     "custom_pending_police_cases": 1,
    //     "custom_permit_type": "All India Permit",
    //     "custom_permit_validity": "2024-04-19",
    //     "custom_permit_status": "Live",
    //     "custom_blacklisting_status": "No pending Challans",
    //     "custom_upload_noc": "/files/B1679.pdf",
    //     "custom_minimum_price": 3500000.0,
    //     "custom_maximum_price": 42000000.0,
    //     "custom_bidding_eligibility": "YES",
    //     "custom_bid_valid_till": "2024-04-23",
    //     "custom_bid_status": "Active",
    //     "custom_bid_commitment": "YES",
    //     "custom_commitment_amount": 200000.0,
    //     "custom_tag_name": "Cover",
    //     "custom_cover_photo": "/files/4A7C3A74-6FA2-4916-AD1C-D2BDCE54EBDB.jpg",
    //     "custom_cover_photo_approved": 0,
    //     "custom_perspective_tag_name_1": "Back",
    //     "custom_perspective_photo_1": "/files/DDAA64BD-E44A-4074-A1B7-19172F12EA03.jpg",
    //     "custom_photo_1_approved": 0,
    //     "custom_perspective_tag_name_2": "Left",
    //     "custom_perspective_photo_2": "/files/636A1C36-DA68-4272-A756-34A5A4BD8CE0.jpg",
    //     "custom_photo_2_approved": 0,
    //     "custom_perspective_tag_name_3": "Right",
    //     "custom_perspective_photo_3": "/files/FD2B3B89-8340-4F23-947B-6BF5F51FDD1D.png",
    //     "custom_photo_3_approved": 0,
    //     "custom_perspective_tag_name_4": "Front",
    //     "custom_perspective_photo_4": "/files/EAF0F2B0-B407-476E-8A2F-AC957A3952D2.jpg",
    //     "custom_photo_4_approved": 0,
    //     "custom_photo_5_approved": 0,
    //     "custom_photo_6_approved": 0,
    //     "custom_photo_7_approved": 0,
    //     "custom_photo_8_approved": 0,
    //     "custom_photo_9_approved": 0,
    //     "customer_code": "",
    //     "published_in_website": 0,
    //     "total_projected_qty": 0.0,
    //     "doctype": "Item",
    //     "customer_items": [],
    //     "custom_accident_table": [],
    //     "reorder_levels": [],
    //     "supplier_items": [],
    //     "item_defaults": [
    //         {
    //             "name": "2708b8158f",
    //             "owner": "divyanshsingh.divs@gmail.com",
    //             "creation": "2024-04-01 23:10:29.626373",
    //             "modified": "2024-06-27 14:49:31.493548",
    //             "modified_by": "testadmin@example.com",
    //             "docstatus": 0,
    //             "idx": 1,
    //             "company": "Liquiconnect Private Limited",
    //             "default_warehouse": "Stores - LPL",
    //             "parent": "STO-ITEM-2024-00005",
    //             "parentfield": "item_defaults",
    //             "parenttype": "Item",
    //             "doctype": "Item Default"
    //         }
    //     ],
    //     "taxes": [],
    //     "attributes": [],
    //     "barcodes": [],
    //     "uoms": [
    //         {
    //             "name": "cf6840d5a1",
    //             "owner": "divyanshsingh.divs@gmail.com",
    //             "creation": "2024-04-01 23:10:29.622390",
    //             "modified": "2024-06-27 14:49:31.493548",
    //             "modified_by": "testadmin@example.com",
    //             "docstatus": 0,
    //             "idx": 1,
    //             "uom": "Nos",
    //             "conversion_factor": 1.0,
    //             "parent": "STO-ITEM-2024-00005",
    //             "parentfield": "uoms",
    //             "parenttype": "Item",
    //             "doctype": "UOM Conversion Detail"
    //         }
    //     ]
    // });
    // emit(VehicleFetchSuccess(vehicleModel:vehicleModel));
    ///SUCCESS
    if(data.isRight){
       emit(VehicleFetchSuccess(vehicleModel: data.right));
    }else{
      emit(VehicleFetchError(error: data.left));
    }
  }
}
