
class VehicleModel {
    String? name;
    String? owner;
    String? creation;
    String? modified;
    String? modifiedBy;
    dynamic docstatus;
    dynamic idx;
    String? namingSeries;
    String? itemCode;
    String? itemName;
    String? itemGroup;
    String? gstHsnCode;
    dynamic isNilExempt;
    dynamic isNonGst;
    String? stockUom;
    dynamic disabled;
    dynamic allowAlternativeItem;
    dynamic isStockItem;
    dynamic hasVariants;
    dynamic includeItemInManufacturing;
    dynamic openingStock;
    dynamic valuationRate;
    dynamic standardRate;
    dynamic isFixedAsset;
    dynamic autoCreateAssets;
    dynamic isGroupedAsset;
    dynamic overDeliveryReceiptAllowance;
    dynamic overBillingAllowance;
    String? description;
    String? brand;
    dynamic shelfLifeInDays;
    String? endOfLife;
    String? defaultMaterialRequestType;
    String? valuationMethod;
    dynamic weightPerUnit;
    dynamic allowNegativeStock;
    dynamic hasBatchNo;
    dynamic createNewBatch;
    dynamic hasExpiryDate;
    dynamic retainSample;
    dynamic sampleQuantity;
    dynamic hasSerialNo;
    String? variantBasedOn;
    dynamic minOrderQty;
    dynamic safetyStock;
    dynamic isPurchaseItem;
    dynamic leadTimeDays;
    dynamic lastPurchaseRate;
    dynamic isCustomerProvidedItem;
    dynamic deliveredBySupplier;
    dynamic enableDeferredExpense;
    dynamic noOfMonthsExp;
    dynamic grantCommission;
    dynamic isSalesItem;
    dynamic maxDiscount;
    dynamic enableDeferredRevenue;
    dynamic noOfMonths;
    dynamic inspectionRequiredBeforePurchase;
    dynamic inspectionRequiredBeforeDelivery;
    dynamic isSubContractedItem;
    String? customTitle;
    String? customRegistrationNumber;
    String? customVehicleRegistration;
    String? customState;
    String? customEngineNumber;
    String? customChassisNumber;
    String? customVehicleClass;
    String? customModel;
    String? customVehicleMake;
    String? customFuelType;
    String? customManufacturingMonthAndYear;
    String? customVehicleType;
    dynamic customGvwInKgs;
    dynamic customUnladenWeightInKgs;
    String? customVehicleColor;
    dynamic customOdometerReadingInKm;
    dynamic customSeatingCapacity;
    dynamic customSleeperCapacity;
    dynamic customNoOfAxels;
    dynamic customMarkAsSold;
    String? customNoOfViews;
    String? customNoOfBids;
    String? customBusType;
    String? customAcStatus;
    String? customWindowType;
    String? customSeatManufacturer;
    String? customBodyManufacturer;
    dynamic customInsuranceDeclaredValue;
    String? customInsuranceValidity;
    dynamic customNcb;
    dynamic customAccidentHistory;
    String? customFitnessCertificate;
    String? customFitnessCertificateValidTill;
    dynamic customPuccCertificate;
    String? customPuccExpiry;
    String? customUploadFitnessCertificate;
    dynamic customNocAvailable;
    dynamic customTaxPaid;
    String? customTaxesPaidUptoDate;
    dynamic customPoliceVerification;
    dynamic customPendingPoliceCases;
    String? customPermitType;
    String? customPermitValidity;
    String? customPermitStatus;
    String? customBlacklistingStatus;
    String? customUploadNoc;
    dynamic customMinimumPrice;
    dynamic customMaximumPrice;
    String? customBiddingEligibility;
    String? customBidValidTill;
    String? customBidStatus;
    String? customBidCommitment;
    dynamic customCommitmentAmount;
    String? customTagName;
    String? customCoverPhoto;
    dynamic customCoverPhotoApproved;
    String? customPerspectiveTagName1;
    String? customPerspectivePhoto1;
    dynamic customPhoto1Approved;
    String? customPerspectiveTagName2;
    String? customPerspectivePhoto2;
    dynamic customPhoto2Approved;
    String? customPerspectiveTagName3;
    String? customPerspectivePhoto3;
    dynamic customPhoto3Approved;
    String? customPerspectiveTagName4;
    String? customPerspectivePhoto4;
    dynamic customPhoto4Approved;
    dynamic customPhoto5Approved;
    dynamic customPhoto6Approved;
    dynamic customPhoto7Approved;
    dynamic customPhoto8Approved;
    dynamic customPhoto9Approved;
    String? customerCode;
    dynamic publishedInWebsite;
    dynamic totalProjectedQty;
    String? doctype;
    List<dynamic>? customerItems;
    List<dynamic>? customAccidentTable;
    List<dynamic>? reorderLevels;
    List<dynamic>? supplierItems;
    List<ItemDefaults>? itemDefaults;
    List<dynamic>? taxes;
    List<dynamic>? attributes;
    List<dynamic>? barcodes;
    List<Uoms>? uoms;

    VehicleModel({this.name, this.owner, this.creation, this.modified, this.modifiedBy, this.docstatus, this.idx, this.namingSeries, this.itemCode, this.itemName, this.itemGroup, this.gstHsnCode, this.isNilExempt, this.isNonGst, this.stockUom, this.disabled, this.allowAlternativeItem, this.isStockItem, this.hasVariants, this.includeItemInManufacturing, this.openingStock, this.valuationRate, this.standardRate, this.isFixedAsset, this.autoCreateAssets, this.isGroupedAsset, this.overDeliveryReceiptAllowance, this.overBillingAllowance, this.description, this.brand, this.shelfLifeInDays, this.endOfLife, this.defaultMaterialRequestType, this.valuationMethod, this.weightPerUnit, this.allowNegativeStock, this.hasBatchNo, this.createNewBatch, this.hasExpiryDate, this.retainSample, this.sampleQuantity, this.hasSerialNo, this.variantBasedOn, this.minOrderQty, this.safetyStock, this.isPurchaseItem, this.leadTimeDays, this.lastPurchaseRate, this.isCustomerProvidedItem, this.deliveredBySupplier, this.enableDeferredExpense, this.noOfMonthsExp, this.grantCommission, this.isSalesItem, this.maxDiscount, this.enableDeferredRevenue, this.noOfMonths, this.inspectionRequiredBeforePurchase, this.inspectionRequiredBeforeDelivery, this.isSubContractedItem, this.customTitle, this.customRegistrationNumber, this.customVehicleRegistration, this.customState, this.customEngineNumber, this.customChassisNumber, this.customVehicleClass, this.customModel, this.customVehicleMake, this.customFuelType, this.customManufacturingMonthAndYear, this.customVehicleType, this.customGvwInKgs, this.customUnladenWeightInKgs, this.customVehicleColor, this.customOdometerReadingInKm, this.customSeatingCapacity, this.customSleeperCapacity, this.customNoOfAxels, this.customMarkAsSold, this.customNoOfViews, this.customNoOfBids, this.customBusType, this.customAcStatus, this.customWindowType, this.customSeatManufacturer, this.customBodyManufacturer, this.customInsuranceDeclaredValue, this.customInsuranceValidity, this.customNcb, this.customAccidentHistory, this.customFitnessCertificate, this.customFitnessCertificateValidTill, this.customPuccCertificate, this.customPuccExpiry, this.customUploadFitnessCertificate, this.customNocAvailable, this.customTaxPaid, this.customTaxesPaidUptoDate, this.customPoliceVerification, this.customPendingPoliceCases, this.customPermitType, this.customPermitValidity, this.customPermitStatus, this.customBlacklistingStatus, this.customUploadNoc, this.customMinimumPrice, this.customMaximumPrice, this.customBiddingEligibility, this.customBidValidTill, this.customBidStatus, this.customBidCommitment, this.customCommitmentAmount, this.customTagName, this.customCoverPhoto, this.customCoverPhotoApproved, this.customPerspectiveTagName1, this.customPerspectivePhoto1, this.customPhoto1Approved, this.customPerspectiveTagName2, this.customPerspectivePhoto2, this.customPhoto2Approved, this.customPerspectiveTagName3, this.customPerspectivePhoto3, this.customPhoto3Approved, this.customPerspectiveTagName4, this.customPerspectivePhoto4, this.customPhoto4Approved, this.customPhoto5Approved, this.customPhoto6Approved, this.customPhoto7Approved, this.customPhoto8Approved, this.customPhoto9Approved, this.customerCode, this.publishedInWebsite, this.totalProjectedQty, this.doctype, this.customerItems, this.customAccidentTable, this.reorderLevels, this.supplierItems, this.itemDefaults, this.taxes, this.attributes, this.barcodes, this.uoms});

    VehicleModel.fromJson(Map<String, dynamic> json) {
        name = json["name"];
        owner = json["owner"];
        creation = json["creation"];
        modified = json["modified"];
        modifiedBy = json["modified_by"];
        docstatus = json["docstatus"];
        idx = json["idx"];
        namingSeries = json["naming_series"];
        itemCode = json["item_code"];
        itemName = json["item_name"];
        itemGroup = json["item_group"];
        gstHsnCode = json["gst_hsn_code"];
        isNilExempt = json["is_nil_exempt"];
        isNonGst = json["is_non_gst"];
        stockUom = json["stock_uom"];
        disabled = json["disabled"];
        allowAlternativeItem = json["allow_alternative_item"];
        isStockItem = json["is_stock_item"];
        hasVariants = json["has_variants"];
        includeItemInManufacturing = json["include_item_in_manufacturing"];
        openingStock = json["opening_stock"];
        valuationRate = json["valuation_rate"];
        standardRate = json["standard_rate"];
        isFixedAsset = json["is_fixed_asset"];
        autoCreateAssets = json["auto_create_assets"];
        isGroupedAsset = json["is_grouped_asset"];
        overDeliveryReceiptAllowance = json["over_delivery_receipt_allowance"];
        overBillingAllowance = json["over_billing_allowance"];
        description = json["description"];
        brand = json["brand"];
        shelfLifeInDays = json["shelf_life_in_days"];
        endOfLife = json["end_of_life"];
        defaultMaterialRequestType = json["default_material_request_type"];
        valuationMethod = json["valuation_method"];
        weightPerUnit = json["weight_per_unit"];
        allowNegativeStock = json["allow_negative_stock"];
        hasBatchNo = json["has_batch_no"];
        createNewBatch = json["create_new_batch"];
        hasExpiryDate = json["has_expiry_date"];
        retainSample = json["retain_sample"];
        sampleQuantity = json["sample_quantity"];
        hasSerialNo = json["has_serial_no"];
        variantBasedOn = json["variant_based_on"];
        minOrderQty = json["min_order_qty"];
        safetyStock = json["safety_stock"];
        isPurchaseItem = json["is_purchase_item"];
        leadTimeDays = json["lead_time_days"];
        lastPurchaseRate = json["last_purchase_rate"];
        isCustomerProvidedItem = json["is_customer_provided_item"];
        deliveredBySupplier = json["delivered_by_supplier"];
        enableDeferredExpense = json["enable_deferred_expense"];
        noOfMonthsExp = json["no_of_months_exp"];
        grantCommission = json["grant_commission"];
        isSalesItem = json["is_sales_item"];
        maxDiscount = json["max_discount"];
        enableDeferredRevenue = json["enable_deferred_revenue"];
        noOfMonths = json["no_of_months"];
        inspectionRequiredBeforePurchase = json["inspection_required_before_purchase"];
        inspectionRequiredBeforeDelivery = json["inspection_required_before_delivery"];
        isSubContractedItem = json["is_sub_contracted_item"];
        customTitle = json["custom_title"];
        customRegistrationNumber = json["custom_registration_number"];
        customVehicleRegistration = json["custom_vehicle_registration"];
        customState = json["custom_state"];
        customEngineNumber = json["custom_engine_number"];
        customChassisNumber = json["custom_chassis_number"];
        customVehicleClass = json["custom_vehicle_class"];
        customModel = json["custom_model"];
        customVehicleMake = json["custom_vehicle_make"];
        customFuelType = json["custom_fuel_type"];
        customManufacturingMonthAndYear = json["custom_manufacturing_month_and_year"];
        customVehicleType = json["custom_vehicle_type"];
        customGvwInKgs = json["custom_gvw_in_kgs"];
        customUnladenWeightInKgs = json["custom_unladen_weight_in_kgs"];
        customVehicleColor = json["custom_vehicle_color"];
        customOdometerReadingInKm = json["custom_odometer_reading_in_km"];
        customSeatingCapacity = json["custom_seating_capacity"];
        customSleeperCapacity = json["custom_sleeper_capacity"];
        customNoOfAxels = json["custom_no_of_axels"];
        customMarkAsSold = json["custom_mark_as_sold"];
        customNoOfViews = json["custom_no_of_views"];
        customNoOfBids = json["custom_no_of_bids"];
        customBusType = json["custom_bus_type"];
        customAcStatus = json["custom_ac_status"];
        customWindowType = json["custom_window_type"];
        customSeatManufacturer = json["custom_seat_manufacturer"];
        customBodyManufacturer = json["custom_body_manufacturer"];
        customInsuranceDeclaredValue = json["custom_insurance_declared_value"];
        customInsuranceValidity = json["custom_insurance_validity"];
        customNcb = json["custom_ncb"];
        customAccidentHistory = json["custom_accident_history"];
        customFitnessCertificate = json["custom_fitness_certificate"];
        customFitnessCertificateValidTill = json["custom_fitness_certificate_valid_till"];
        customPuccCertificate = json["custom_pucc_certificate"];
        customPuccExpiry = json["custom_pucc_expiry"];
        customUploadFitnessCertificate = json["custom_upload_fitness_certificate"];
        customNocAvailable = json["custom_noc_available"];
        customTaxPaid = json["custom_tax_paid"];
        customTaxesPaidUptoDate = json["custom_taxes_paid_upto_date"];
        customPoliceVerification = json["custom_police_verification"];
        customPendingPoliceCases = json["custom_pending_police_cases"];
        customPermitType = json["custom_permit_type"];
        customPermitValidity = json["custom_permit_validity"];
        customPermitStatus = json["custom_permit_status"];
        customBlacklistingStatus = json["custom_blacklisting_status"];
        customUploadNoc = json["custom_upload_noc"];
        customMinimumPrice = json["custom_minimum_price"];
        customMaximumPrice = json["custom_maximum_price"];
        customBiddingEligibility = json["custom_bidding_eligibility"];
        customBidValidTill = json["custom_bid_valid_till"];
        customBidStatus = json["custom_bid_status"];
        customBidCommitment = json["custom_bid_commitment"];
        customCommitmentAmount = json["custom_commitment_amount"];
        customTagName = json["custom_tag_name"];
        customCoverPhoto = json["custom_cover_photo"];
        customCoverPhotoApproved = json["custom_cover_photo_approved"];
        customPerspectiveTagName1 = json["custom_perspective_tag_name_1"];
        customPerspectivePhoto1 = json["custom_perspective_photo_1"];
        customPhoto1Approved = json["custom_photo_1_approved"];
        customPerspectiveTagName2 = json["custom_perspective_tag_name_2"];
        customPerspectivePhoto2 = json["custom_perspective_photo_2"];
        customPhoto2Approved = json["custom_photo_2_approved"];
        customPerspectiveTagName3 = json["custom_perspective_tag_name_3"];
        customPerspectivePhoto3 = json["custom_perspective_photo_3"];
        customPhoto3Approved = json["custom_photo_3_approved"];
        customPerspectiveTagName4 = json["custom_perspective_tag_name_4"];
        customPerspectivePhoto4 = json["custom_perspective_photo_4"];
        customPhoto4Approved = json["custom_photo_4_approved"];
        customPhoto5Approved = json["custom_photo_5_approved"];
        customPhoto6Approved = json["custom_photo_6_approved"];
        customPhoto7Approved = json["custom_photo_7_approved"];
        customPhoto8Approved = json["custom_photo_8_approved"];
        customPhoto9Approved = json["custom_photo_9_approved"];
        customerCode = json["customer_code"];
        publishedInWebsite = json["published_in_website"];
        totalProjectedQty = json["total_projected_qty"];
        doctype = json["doctype"];
        customerItems = json["customer_items"] ?? [];
        customAccidentTable = json["custom_accident_table"] ?? [];
        reorderLevels = json["reorder_levels"] ?? [];
        supplierItems = json["supplier_items"] ?? [];
        itemDefaults = json["item_defaults"] == null ? null : (json["item_defaults"] as List).map((e) => ItemDefaults.fromJson(e)).toList();
        taxes = json["taxes"] ?? [];
        attributes = json["attributes"] ?? [];
        barcodes = json["barcodes"] ?? [];
        uoms = json["uoms"] == null ? null : (json["uoms"] as List).map((e) => Uoms.fromJson(e)).toList();
    }

    Map<String, dynamic> toJson() {
        final Map<String, dynamic> _data = <String, dynamic>{};
        _data["name"] = name;
        _data["owner"] = owner;
        _data["creation"] = creation;
        _data["modified"] = modified;
        _data["modified_by"] = modifiedBy;
        _data["docstatus"] = docstatus;
        _data["idx"] = idx;
        _data["naming_series"] = namingSeries;
        _data["item_code"] = itemCode;
        _data["item_name"] = itemName;
        _data["item_group"] = itemGroup;
        _data["gst_hsn_code"] = gstHsnCode;
        _data["is_nil_exempt"] = isNilExempt;
        _data["is_non_gst"] = isNonGst;
        _data["stock_uom"] = stockUom;
        _data["disabled"] = disabled;
        _data["allow_alternative_item"] = allowAlternativeItem;
        _data["is_stock_item"] = isStockItem;
        _data["has_variants"] = hasVariants;
        _data["include_item_in_manufacturing"] = includeItemInManufacturing;
        _data["opening_stock"] = openingStock;
        _data["valuation_rate"] = valuationRate;
        _data["standard_rate"] = standardRate;
        _data["is_fixed_asset"] = isFixedAsset;
        _data["auto_create_assets"] = autoCreateAssets;
        _data["is_grouped_asset"] = isGroupedAsset;
        _data["over_delivery_receipt_allowance"] = overDeliveryReceiptAllowance;
        _data["over_billing_allowance"] = overBillingAllowance;
        _data["description"] = description;
        _data["brand"] = brand;
        _data["shelf_life_in_days"] = shelfLifeInDays;
        _data["end_of_life"] = endOfLife;
        _data["default_material_request_type"] = defaultMaterialRequestType;
        _data["valuation_method"] = valuationMethod;
        _data["weight_per_unit"] = weightPerUnit;
        _data["allow_negative_stock"] = allowNegativeStock;
        _data["has_batch_no"] = hasBatchNo;
        _data["create_new_batch"] = createNewBatch;
        _data["has_expiry_date"] = hasExpiryDate;
        _data["retain_sample"] = retainSample;
        _data["sample_quantity"] = sampleQuantity;
        _data["has_serial_no"] = hasSerialNo;
        _data["variant_based_on"] = variantBasedOn;
        _data["min_order_qty"] = minOrderQty;
        _data["safety_stock"] = safetyStock;
        _data["is_purchase_item"] = isPurchaseItem;
        _data["lead_time_days"] = leadTimeDays;
        _data["last_purchase_rate"] = lastPurchaseRate;
        _data["is_customer_provided_item"] = isCustomerProvidedItem;
        _data["delivered_by_supplier"] = deliveredBySupplier;
        _data["enable_deferred_expense"] = enableDeferredExpense;
        _data["no_of_months_exp"] = noOfMonthsExp;
        _data["grant_commission"] = grantCommission;
        _data["is_sales_item"] = isSalesItem;
        _data["max_discount"] = maxDiscount;
        _data["enable_deferred_revenue"] = enableDeferredRevenue;
        _data["no_of_months"] = noOfMonths;
        _data["inspection_required_before_purchase"] = inspectionRequiredBeforePurchase;
        _data["inspection_required_before_delivery"] = inspectionRequiredBeforeDelivery;
        _data["is_sub_contracted_item"] = isSubContractedItem;
        _data["custom_title"] = customTitle;
        _data["custom_registration_number"] = customRegistrationNumber;
        _data["custom_vehicle_registration"] = customVehicleRegistration;
        _data["custom_state"] = customState;
        _data["custom_engine_number"] = customEngineNumber;
        _data["custom_chassis_number"] = customChassisNumber;
        _data["custom_vehicle_class"] = customVehicleClass;
        _data["custom_model"] = customModel;
        _data["custom_vehicle_make"] = customVehicleMake;
        _data["custom_fuel_type"] = customFuelType;
        _data["custom_manufacturing_month_and_year"] = customManufacturingMonthAndYear;
        _data["custom_vehicle_type"] = customVehicleType;
        _data["custom_gvw_in_kgs"] = customGvwInKgs;
        _data["custom_unladen_weight_in_kgs"] = customUnladenWeightInKgs;
        _data["custom_vehicle_color"] = customVehicleColor;
        _data["custom_odometer_reading_in_km"] = customOdometerReadingInKm;
        _data["custom_seating_capacity"] = customSeatingCapacity;
        _data["custom_sleeper_capacity"] = customSleeperCapacity;
        _data["custom_no_of_axels"] = customNoOfAxels;
        _data["custom_mark_as_sold"] = customMarkAsSold;
        _data["custom_no_of_views"] = customNoOfViews;
        _data["custom_no_of_bids"] = customNoOfBids;
        _data["custom_bus_type"] = customBusType;
        _data["custom_ac_status"] = customAcStatus;
        _data["custom_window_type"] = customWindowType;
        _data["custom_seat_manufacturer"] = customSeatManufacturer;
        _data["custom_body_manufacturer"] = customBodyManufacturer;
        _data["custom_insurance_declared_value"] = customInsuranceDeclaredValue;
        _data["custom_insurance_validity"] = customInsuranceValidity;
        _data["custom_ncb"] = customNcb;
        _data["custom_accident_history"] = customAccidentHistory;
        _data["custom_fitness_certificate"] = customFitnessCertificate;
        _data["custom_fitness_certificate_valid_till"] = customFitnessCertificateValidTill;
        _data["custom_pucc_certificate"] = customPuccCertificate;
        _data["custom_pucc_expiry"] = customPuccExpiry;
        _data["custom_upload_fitness_certificate"] = customUploadFitnessCertificate;
        _data["custom_noc_available"] = customNocAvailable;
        _data["custom_tax_paid"] = customTaxPaid;
        _data["custom_taxes_paid_upto_date"] = customTaxesPaidUptoDate;
        _data["custom_police_verification"] = customPoliceVerification;
        _data["custom_pending_police_cases"] = customPendingPoliceCases;
        _data["custom_permit_type"] = customPermitType;
        _data["custom_permit_validity"] = customPermitValidity;
        _data["custom_permit_status"] = customPermitStatus;
        _data["custom_blacklisting_status"] = customBlacklistingStatus;
        _data["custom_upload_noc"] = customUploadNoc;
        _data["custom_minimum_price"] = customMinimumPrice;
        _data["custom_maximum_price"] = customMaximumPrice;
        _data["custom_bidding_eligibility"] = customBiddingEligibility;
        _data["custom_bid_valid_till"] = customBidValidTill;
        _data["custom_bid_status"] = customBidStatus;
        _data["custom_bid_commitment"] = customBidCommitment;
        _data["custom_commitment_amount"] = customCommitmentAmount;
        _data["custom_tag_name"] = customTagName;
        _data["custom_cover_photo"] = customCoverPhoto;
        _data["custom_cover_photo_approved"] = customCoverPhotoApproved;
        _data["custom_perspective_tag_name_1"] = customPerspectiveTagName1;
        _data["custom_perspective_photo_1"] = customPerspectivePhoto1;
        _data["custom_photo_1_approved"] = customPhoto1Approved;
        _data["custom_perspective_tag_name_2"] = customPerspectiveTagName2;
        _data["custom_perspective_photo_2"] = customPerspectivePhoto2;
        _data["custom_photo_2_approved"] = customPhoto2Approved;
        _data["custom_perspective_tag_name_3"] = customPerspectiveTagName3;
        _data["custom_perspective_photo_3"] = customPerspectivePhoto3;
        _data["custom_photo_3_approved"] = customPhoto3Approved;
        _data["custom_perspective_tag_name_4"] = customPerspectiveTagName4;
        _data["custom_perspective_photo_4"] = customPerspectivePhoto4;
        _data["custom_photo_4_approved"] = customPhoto4Approved;
        _data["custom_photo_5_approved"] = customPhoto5Approved;
        _data["custom_photo_6_approved"] = customPhoto6Approved;
        _data["custom_photo_7_approved"] = customPhoto7Approved;
        _data["custom_photo_8_approved"] = customPhoto8Approved;
        _data["custom_photo_9_approved"] = customPhoto9Approved;
        _data["customer_code"] = customerCode;
        _data["published_in_website"] = publishedInWebsite;
        _data["total_projected_qty"] = totalProjectedQty;
        _data["doctype"] = doctype;
        if(customerItems != null) {
            _data["customer_items"] = customerItems;
        }
        if(customAccidentTable != null) {
            _data["custom_accident_table"] = customAccidentTable;
        }
        if(reorderLevels != null) {
            _data["reorder_levels"] = reorderLevels;
        }
        if(supplierItems != null) {
            _data["supplier_items"] = supplierItems;
        }
        if(itemDefaults != null) {
            _data["item_defaults"] = itemDefaults?.map((e) => e.toJson()).toList();
        }
        if(taxes != null) {
            _data["taxes"] = taxes;
        }
        if(attributes != null) {
            _data["attributes"] = attributes;
        }
        if(barcodes != null) {
            _data["barcodes"] = barcodes;
        }
        if(uoms != null) {
            _data["uoms"] = uoms?.map((e) => e.toJson()).toList();
        }
        return _data;
    }
}

class Uoms {
    String? name;
    String? owner;
    String? creation;
    String? modified;
    String? modifiedBy;
    dynamic docstatus;
    dynamic idx;
    String? uom;
    dynamic conversionFactor;
    String? parent;
    String? parentfield;
    String? parenttype;
    String? doctype;

    Uoms({this.name, this.owner, this.creation, this.modified, this.modifiedBy, this.docstatus, this.idx, this.uom, this.conversionFactor, this.parent, this.parentfield, this.parenttype, this.doctype});

    Uoms.fromJson(Map<String, dynamic> json) {
        name = json["name"];
        owner = json["owner"];
        creation = json["creation"];
        modified = json["modified"];
        modifiedBy = json["modified_by"];
        docstatus = json["docstatus"];
        idx = json["idx"];
        uom = json["uom"];
        conversionFactor = json["conversion_factor"];
        parent = json["parent"];
        parentfield = json["parentfield"];
        parenttype = json["parenttype"];
        doctype = json["doctype"];
    }

    Map<String, dynamic> toJson() {
        final Map<String, dynamic> _data = <String, dynamic>{};
        _data["name"] = name;
        _data["owner"] = owner;
        _data["creation"] = creation;
        _data["modified"] = modified;
        _data["modified_by"] = modifiedBy;
        _data["docstatus"] = docstatus;
        _data["idx"] = idx;
        _data["uom"] = uom;
        _data["conversion_factor"] = conversionFactor;
        _data["parent"] = parent;
        _data["parentfield"] = parentfield;
        _data["parenttype"] = parenttype;
        _data["doctype"] = doctype;
        return _data;
    }
}

class ItemDefaults {
    String? name;
    String? owner;
    String? creation;
    String? modified;
    String? modifiedBy;
    dynamic docstatus;
    dynamic idx;
    String? company;
    String? defaultWarehouse;
    String? parent;
    String? parentfield;
    String? parenttype;
    String? doctype;

    ItemDefaults({this.name, this.owner, this.creation, this.modified, this.modifiedBy, this.docstatus, this.idx, this.company, this.defaultWarehouse, this.parent, this.parentfield, this.parenttype, this.doctype});

    ItemDefaults.fromJson(Map<String, dynamic> json) {
        name = json["name"];
        owner = json["owner"];
        creation = json["creation"];
        modified = json["modified"];
        modifiedBy = json["modified_by"];
        docstatus = json["docstatus"];
        idx = json["idx"];
        company = json["company"];
        defaultWarehouse = json["default_warehouse"];
        parent = json["parent"];
        parentfield = json["parentfield"];
        parenttype = json["parenttype"];
        doctype = json["doctype"];
    }

    Map<String, dynamic> toJson() {
        final Map<String, dynamic> _data = <String, dynamic>{};
        _data["name"] = name;
        _data["owner"] = owner;
        _data["creation"] = creation;
        _data["modified"] = modified;
        _data["modified_by"] = modifiedBy;
        _data["docstatus"] = docstatus;
        _data["idx"] = idx;
        _data["company"] = company;
        _data["default_warehouse"] = defaultWarehouse;
        _data["parent"] = parent;
        _data["parentfield"] = parentfield;
        _data["parenttype"] = parenttype;
        _data["doctype"] = doctype;
        return _data;
    }
}